import { tx, useLanguage, translateAuthoredCode } from '@react-quest/localization';
import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { challenges, chapters, challengeKinds, getChallenge, isChallengeAvailable } from '@react-quest/challenges';
import { CodeRuntime, evaluateAnswers, idleStatus, type RuntimeKind, type RuntimeStatus } from '@react-quest/learning-engine';
import type { Challenge, CodeAnalysis, EvaluationResult, RuntimeTrace } from '@react-quest/shared';
import { useAppDispatch, useAppSelector } from '../store';
import { answerQuestion, completeChallenge, revealHint, revealSolution, saveDraft, saveProjectStorage, selectChallenge } from '../store/progressSlice';
import { getDraft, getLevelInfo, getProgressTotals, hintFactor } from '../store/progression';
import { Icon } from './Icon';
import { SiteLogo } from './SiteLogo';
import { ResizableWorkspace, type WorkspacePanel } from './ResizableWorkspace';

import { ProjectShowcase } from './ProjectShowcase';
import { TeachingLesson } from './TeachingLesson';
const CodeEditor = lazy(() => import('./CodeEditor'));

export function ComputerMode({ onExit, onHub, dailyId }: { onExit: () => void; onHub: () => void; dailyId?: string }) {
  useLanguage();
  const selected = useAppSelector(s => s.progress.selectedChallengeId), challenge = getChallenge(selected) ?? challenges[0]!;
  const learned = useAppSelector(s => s.progress.learnedLessons.includes(challenge.id));
  const [review, setReview] = useState<string>();
  if (!learned || review === challenge.id) return <TeachingLesson key={challenge.id} challenge={challenge} onExit={onExit} onHub={onHub} onFinish={() => setReview(undefined)} review={learned} daily={dailyId === challenge.id}/>;
  return <ChallengeWorkspace key={challenge.id} challenge={challenge} onExit={onExit} onHub={onHub} daily={dailyId === challenge.id} onLearn={() => setReview(challenge.id)}/>;
}
function ChallengeWorkspace({ challenge, onExit, onHub, daily, onLearn }: { challenge: Challenge; onExit: () => void; onHub: () => void; daily: boolean; onLearn: () => void }) {
  const language = useLanguage();
  const dispatch = useAppDispatch(), progress = useAppSelector(s => s.progress);
  const savedDraft = progress.drafts[challenge.id];
  const code = savedDraft ?? translateAuthoredCode(getDraft(progress, challenge), language);
  useEffect(() => {
    if (language === 'en' && savedDraft === undefined) dispatch(saveDraft({ id: challenge.id, code }));
  }, [language, savedDraft, dispatch, challenge.id, code]);
  const completed = progress.completedLessons.includes(challenge.id), {xp,coins} = getProgressTotals(progress), level = getLevelInfo(xp);
  const help = progress.assistance[challenge.id] ?? {hints:0,solution:false}, rewardXP = Math.floor(challenge.xp*hintFactor(help.hints,help.solution));
  const answers = progress.answers[challenge.id] ?? {};
  const frame = useRef<HTMLIFrameElement>(null), mounted = useRef(false);
  const [status,setStatus] = useState<RuntimeStatus>(idleStatus), [analysis,setAnalysis] = useState<CodeAnalysis>(), [trace,setTrace] = useState<RuntimeTrace[]>([]), [renders,setRenders] = useState<Record<string,number>>({});
  const storageKey = challenge.project?.id ?? challenge.id;
  const [runtime] = useState(()=>new CodeRuntime(setStatus,{analysis:setAnalysis,trace:(events,counts)=>{setTrace(events);setRenders(counts);},initialStorage:progress.projectStorage[storageKey] ?? {},storage:values=>dispatch(saveProjectStorage({id:storageKey,values}))}));
  const [kind,setKind] = useState<RuntimeKind>('local'),[busy,setBusy] = useState(false),[result,setResult] = useState<EvaluationResult>(),[reward,setReward] = useState(false),[chapterFilter,setChapterFilter] = useState(String(challenge.chapterId ?? 1)),[inspector,setInspector] = useState('trace');
  const [showcase, setShowcase] = useState(false);
  const quizOnly = challenge.tests.every(t=>t.questionId);
  const next = [...challenges.slice(challenges.indexOf(challenge)+1),...challenges].find(c=>c.id!==challenge.id && isChallengeAvailable(c) && !progress.completedLessons.includes(c.id));
  useEffect(()=>{mounted.current=true;const detach=runtime.attach(frame.current!);return()=>{mounted.current=false;detach();};},[runtime]);
  const execute = async(submit:boolean)=>{
    if(busy)return;setBusy(true);setResult(undefined);setReward(false);
    try {
      if(submit){const evaluation=quizOnly?evaluateAnswers(challenge,answers):await runtime.evaluate(challenge,code,kind,answers);if(!mounted.current)return;setResult(evaluation);dispatch(completeChallenge({id:challenge.id,source:code,result:evaluation,answers,daily}));if(evaluation.passed)setReward(!completed);}
      else {setTrace([]);await runtime.run(code,kind);}
    }catch{/* Runtime exposes the actionable error. */}finally{if(mounted.current)setBusy(false);}
  };
  const questions = <div className="knowledge-questions">{challenge.questions?.map(q=><fieldset key={q.id} disabled={busy}><legend>{tx(q.prompt)}</legend>{q.code && <pre dir="ltr">{q.code}</pre>}{q.options.map((option,i)=><label key={option}><input type="radio" name={q.id} checked={answers[q.id]===i} onChange={()=>{dispatch(answerQuestion({id:challenge.id,question:q.id,answer:i}));setResult(undefined);}}/>{tx(option)}</label>)}{result && <p className={answers[q.id]===q.answer?'answer-correct':'answer-wrong'}>{tx(q.explanation)}</p>}</fieldset>)}</div>;
  const panels: WorkspacePanel[] = [
    {id:"path",title:"مسیر یادگیری",size:180,height:320,minWidth:145,minHeight:180,content:(<aside className="lesson-sidebar"><span className="chapter-label" dir="ltr">YOUR LEARNING PATH</span><h2>{tx("یاد بگیر. بساز. مسلط شو.")}</h2><label className="chapter-select">{tx("فصل")}<select aria-label={tx("فصل آموزشی")} value={chapterFilter} disabled={busy} onChange={e=>setChapterFilter(e.target.value)}><option value="all">{tx("همهٔ تمرین‌ها")}</option>{chapters.map(c=><option key={c.id} value={c.id}>{tx(c.id)}. {tx(c.title)}</option>)}</select></label><nav aria-label={tx("تمرین‌های React")}>{challenges.filter(c=>chapterFilter==='all'||String(c.chapterId)===chapterFilter).map(item=>{const available=isChallengeAvailable(item),done=progress.completedLessons.includes(item.id);return <button key={item.id} data-challenge={item.id} className={`lesson-nav ${item.id===challenge.id?'selected':''} ${done?'done':''}`} disabled={!available||busy} aria-current={item.id===challenge.id?'step':undefined} onClick={()=>dispatch(selectChallenge(item.id))}><span className="lesson-number">{done?'✓':available?'○':<Icon name="lock" size={13}/>}</span><span><b>{tx(item.title)}</b><small>{tx(item.mastery?'گواه تسلط':challengeKinds[item.kind??'write'])}</small></span></button>;})}</nav><div className="lesson-reward"><span>{tx(challenge.mastery?'تمرین تازه · بدون راهنما':'پاداش با راهنمای فعلی')}</span><b dir="ltr">+{tx(rewardXP)} XP <small>+{tx(challenge.coins)} COINS</small></b><span>{tx(challenge.minutes)}{tx(" دقیقه · سختی ")}{tx(challenge.difficulty)}/5</span></div></aside>)},
    {id:"mission",title:"شرح تمرین",size:260,height:520,minWidth:230,minHeight:270,content:(<section className="challenge-content"><div className="challenge-heading"><span>{tx("فصل ")}{tx(challenge.chapterId)} · {tx(challengeKinds[challenge.kind??'write'])}</span><h1>{tx(challenge.title)}</h1><p>{tx(challenge.description)}</p>{challenge.mastery&&<b className="mastery-label">{tx("گواه تسلط · بدون راهنما و پاسخ آماده")}</b>}{daily&&<b className="daily-label">{tx("تمرین امروز · +20 XP یک بار در روز")}</b>}</div><div className="detail-tabs"><span className="practice-stage">{tx("۲. تمرین")}</span><button onClick={onLearn}>{tx("مرور درس · رایگان")}</button></div><ol className="requirements">{challenge.instructions.map(i=><li key={i}>{tx(i)}</li>)}</ol>{tx(!quizOnly&&questions)}<div className="hint-box"><button onClick={()=>dispatch(revealHint(challenge.id))} disabled={challenge.mastery||help.hints>=Math.min(4,challenge.hints.length)}>{tx("✧ راهنمایی مرحله‌ای ")}<span>{tx(help.hints)}/4</span></button><small>{tx(challenge.mastery?'برای تسلط، تمرین را مستقل حل کن.':'پاداش پس از راهنما: ۹۰٪، ۷۵٪، ۶۰٪، ۴۵٪؛ پاسخ آماده: ۳۰٪.')}</small>{challenge.hints.slice(0,help.hints).map(h=><p key={h}>{tx(h)}</p>)}</div>{challenge.solution&&!quizOnly&&!challenge.mastery&&<details className="solution-box" onToggle={e=>{if(e.currentTarget.open)dispatch(revealSolution(challenge.id));}}><summary>{tx("دیدن پاسخ آموزشی · پاداش ۳۰٪")}</summary>{help.solution&&<><pre dir="ltr">{challenge.solution}</pre><button disabled={busy} onClick={()=>dispatch(saveDraft({id:challenge.id,code:challenge.solution!}))}>{tx("قرار دادن در ویرایشگر")}</button></>}</details>}
    {completed&&!result&&next&&<button className="next-lesson-button" onClick={()=>dispatch(selectChallenge(next.id))}>{tx("مأموریت بعدی: ")}{tx(next.title)} ←</button>}{result&&<div className={`evaluation-result ${result.passed?'passed':''}`} role="status"><h3>{tx(result.passed?challenge.mastery?(progress.receipts[challenge.id]?.mastery?'تسلط ثبت شد!':'آزمون موفق بود؛ یک گواه تازه برای تسلط انتخاب کن.'):'مأموریت انجام شد!':'یک قدم تا موفقیت')}</h3><span className="test-score">{tx(result.score)}{tx("% تست‌ها موفق شدند")}</span>{challenge.kind==='boss'&&<div className="boss-health"><b>{tx("قدرت باگ‌ها: ")}{tx(result.tests.filter(t=>!t.passed).length)}/{tx(result.tests.length)}</b><div><i style={{width:`${100-result.score}%`}}/></div></div>}<ul>{result.tests.map(t=><li key={t.id}><span>{tx(t.passed?'✓':'×')}</span><div>{tx(t.name)}{!t.passed&&<small>{tx(t.message)}</small>}</div></li>)}</ul>{result.quality&&<details className="quality-scores"><summary>{tx("کیفیت کد و شواهد")}</summary>{result.quality.map(q=><p key={q.name}><b>{tx(q.name)} {tx(q.score===null?'—':`${q.score}%`)}</b><small>{tx(q.evidence)}</small></p>)}</details>}{result.passed&&<><div className="reward-message">{tx(reward?`+${rewardXP} XP و +${challenge.coins} سکه گرفتی.`:'این تمرین قبلاً پاداش گرفته؛ مرور موفق ثبت شد.')}</div>{next&&<button className="next-lesson-button" onClick={()=>dispatch(selectChallenge(next.id))}>{tx("مأموریت بعدی: ")}{tx(next.title)} ←</button>}<button className="next-lesson-button" onClick={onHub}>{tx("مشاهدهٔ نقشهٔ دانش ←")}</button></>}</div>}</section>)},
    {id:"editor",title:quizOnly ? "سؤال‌ها" : "ویرایشگر",size:360,height:520,minWidth:280,minHeight:280,content:(<section className={`coding-area ${quizOnly?'quiz-area':''}`}>{quizOnly?<><div className="quiz-heading"><span className="eyebrow">READ / PREDICT / EXPLAIN</span><h2>{tx("قبل از اجرا، فکر کن.")}</h2><p>{tx("پاسخ را انتخاب کن و دلیلش را بعد از بررسی بخوان.")}</p></div>{tx(questions)}</>:<><div className="code-filebar" dir="ltr"><span><i/>App.jsx</span><small>{tx(challenge.project?`${challenge.project.id} · ${challenge.project.step}`:'JavaScript · React 19')}</small></div><div className="editor-container" dir="ltr"><Suspense fallback={<div className="editor-loading">{tx("در حال آماده‌سازی ویرایشگر…")}</div>}><CodeEditor value={code} readOnly={busy} onChange={value=>{dispatch(saveDraft({id:challenge.id,code:value}));setResult(undefined);setReward(false);}} onRun={()=>{void execute(false);}}/></Suspense></div></>}<div className="coding-actions"><button className="submit-code" disabled={busy} onClick={()=>{void execute(true);}}>{tx(busy?'در حال بررسی…':'ارسال پاسخ')}<Icon name="arrow" size={16}/></button>{!quizOnly&&<><button disabled={busy} onClick={()=>{void execute(false);}}>{tx("▶ اجرای کد")}</button>{challenge.project && <button disabled={busy} onClick={() => { dispatch(saveDraft({id:challenge.id,code})); setShowcase(true); }}>{tx("نمایش ساختهٔ من در سایت ↗")}</button>}<button className="reset-code" disabled={busy} onClick={()=>{dispatch(saveDraft({id:challenge.id,code:translateAuthoredCode(challenge.starterFiles['src/App.jsx']!, language)}));setResult(undefined);}}>{tx("بازنشانی")}</button></>}</div></section>)},
    {id:"preview",title:"پیش‌نمایش و اجرا",size:300,height:520,minWidth:240,minHeight:240,content:(<section className="preview-area"><div className="preview-heading"><b>{tx(quizOnly?'مفهوم در عمل':'پیش‌نمایش زنده')}</b><span className={`runtime-dot ${status.phase==='ready'?'ready':''}`}/><small>{tx(status.engine==='webcontainer'?'Vite · pnpm':'React')}</small></div><iframe ref={frame} title={tx("پیش‌نمایش React")} sandbox="allow-scripts" className="react-preview" hidden={quizOnly}/>{quizOnly?<div className="quiz-lesson-summary"><h3>{tx("از توضیح به تمرین")}</h3><p>{tx("این سؤال بر اساس درس قبلی است. هر زمان لازم بود، مثال‌ها را دوباره مرور کن.")}</p><button onClick={onLearn}>{tx("مرور درس · رایگان")}</button></div>:<><div className={`runtime-status ${status.phase==='error'?'error':''}`} role="status"><span>{tx(status.message)}</span>{status.fallbackReason&&<small>{tx("اجرای محلی فعال شد: ")}{tx(status.fallbackReason)}</small>}</div><div className="runtime-options"><label htmlFor="runtime-kind">{tx("روش اجرا")}</label><select id="runtime-kind" value={kind} disabled={busy} onChange={e=>setKind(e.target.value as RuntimeKind)}><option value="local">{tx("اجرای محلی")}</option><option value="auto">{tx("خودکار")}</option><option value="webcontainer">{tx("پروژهٔ Vite (pnpm)")}</option></select></div><section className="execution-inspector" aria-label={tx("مشاهدهٔ اجرای React")}><div className="detail-tabs"><button className={inspector==='trace'?'active':''} onClick={()=>setInspector('trace')}>{tx("مشاهدهٔ اجرا")}</button><button className={inspector==='tree'?'active':''} onClick={()=>setInspector('tree')}>{tx("درخت و Props")}</button></div>{inspector==='trace'?<><p>{tx("رویدادهای واقعی کد اجراشده؛ آخرین ۲۴ رویداد.")}</p><ol className="trace-events" dir="ltr">{trace.map((t,i)=><li key={`${i}-${t.at}`} data-kind={t.kind}><span>{tx(t.kind)}</span><b>{tx(t.label)}</b>{t.detail&&<small>{tx(t.detail)}</small>}</li>)}</ol>{!trace.length&&<small>{tx("کد را اجرا و با پیش‌نمایش تعامل کن.")}</small>}</>:<><p>{tx("ارتباط‌های JSX از تحلیل کد؛ شمارنده، تعداد فراخوانی واقعی تابع کامپوننت است.")}</p><div className="component-nodes" dir="ltr">{analysis?.components.map(c=><div key={c}><b>{tx(c)}</b><span>{tx(renders[c]??0)} calls</span></div>)}</div><ul className="component-edges" dir="ltr">{analysis?.tree?.map((e,i)=><li key={i}>{tx(e.parent)} → {tx(e.child)}<small>Props: {tx(e.props.join(', ')||'—')}</small></li>)}</ul>{trace.filter(t=>t.kind==='props').slice(-5).map((t,i)=><pre key={i} dir="ltr">{t.label}: {t.detail}</pre>)}{analysis?.warnings?.map(w=><p key={w}>{tx(w)}</p>)}</>}</section></>}{status.logs&&<details className="runtime-console"><summary>{tx("گزارش اجرا")}</summary><pre dir="ltr">{status.logs}</pre></details>}</section>)}
  ];
  return <section className="computer-screen" aria-label={tx("محیط آموزش React")}><header className="computer-header"><div className="computer-brand"><SiteLogo /><b dir="ltr">reactquest<span>.</span></b><button className="map-button" onClick={onHub}>{tx("نقشهٔ دانش ↗")}</button></div><div className="learning-stats"><span>{tx("سطح ")}<b>{tx(level.level)}</b></span><span dir="ltr"><b data-testid="total-xp">{tx(xp)}</b> XP</span><span>{tx(coins)}{tx(" سکه")}</span><button className="back-room" onClick={onExit}>{tx("بازگشت به اتاق ")}<Icon name="arrow" size={17}/></button></div></header><ResizableWorkspace storageKey="practice" panels={panels}/>{showcase && <ProjectShowcase challenge={challenge} onClose={() => setShowcase(false)} />}</section>;
}
