import { tx, useLanguage } from '@react-quest/localization';
import { useState } from 'react';
import { challenges, chapters, challengeKinds, getChapterLesson, isChallengeAvailable, projectDefinitions, rooms, skills } from '@react-quest/challenges';
import type { Challenge } from '@react-quest/shared';
import { useAppSelector } from '../store';
import { dailyChallenge, dayKey, dueChallenges, getProgressTotals, getSkillStatus, getStreak, isRoomAvailable, recommendations, skillLabels } from '../store/progression';
import { TeachingStepContent } from './TeachingLesson';

type Props = { onClose: () => void; onSelect: (id: string, daily?: boolean) => void; onVisit: (id: string) => void };
export function LearningHub({ onClose, onSelect, onVisit }: Props) {
  useLanguage();
  const progress = useAppSelector(s => s.progress);
  const [tab, setTab] = useState('map'), [reading, setReading] = useState(1);
  const totals = getProgressTotals(progress), daily = dailyChallenge(progress), due = dueChallenges(progress);
  const open = (c: Challenge) => onSelect(c.id);
  const entry = (chapter: number) => challenges.find(c => c.chapterId === chapter && !progress.completedLessons.includes(c.id) && isChallengeAvailable(c, progress.completedLessons)) ?? challenges.find(c => c.chapterId === chapter && isChallengeAvailable(c, progress.completedLessons));
  const chapter = getChapterLesson(reading);
  const readChapter = (id: number) => { setReading(id); setTab('library'); };
  return <section className="learning-hub" aria-label={tx("مرکز یادگیری")}><header className="hub-header"><div><span className="eyebrow" dir="ltr">LEARN. BUILD. UNDERSTAND.</span><h1>{tx("مسیر یادگیری تو")}</h1></div><button className="back-room" onClick={onClose}>{tx("بستن نقشه ×")}</button></header><div className="hub-scroll"><div className="hub-intro"><div><p>{tx("از آشنایی تا تسلط، با تمرین و ساختن.")}</p><span>{tx(progress.completedLessons.length)}{tx(" از ")}{tx(challenges.length)}{tx(" تمرین · ")}{tx(skills.filter(s => getSkillStatus(progress, s.id) === 'mastered').length)}{tx(" مهارت مسلط")}</span></div><div className="hub-stat"><b>{tx(totals.xp)}</b><span>XP</span></div><div className="hub-stat"><b>{tx(getStreak(progress))}</b><span>{tx("روز تمرین پیوسته")}</span></div></div><section className="recommendation-strip"><div className="daily-card"><span className="eyebrow">{tx("تمرین امروز · پاداش آرام +20 XP")}</span><h3>{tx(daily.title)}</h3><p>{tx(progress.dailyDays.includes(dayKey()) ? 'تمرین امروز انجام شد. پاداش دوباره ثبت نمی‌شود.' : 'یک تمرین کافی است. از دست‌دادن یک روز، XP تو را کم نمی‌کند.')}</p><button onClick={() => onSelect(daily.id, true)}>{tx("تمرین امروز ←")}</button></div><div className="recommended-card"><span className="eyebrow">{tx("قدم پیشنهادی · بر اساس پیشرفت و خطاها")}</span>{recommendations(progress).map(c => <button key={c.id} onClick={() => open(c)}><span>{tx(c.title)}</span><small>{tx(due.some(x => x.id === c.id) ? 'مرور فاصله‌دار' : c.mastery ? 'اثبات تسلط بدون راهنما' : challengeKinds[c.kind ?? 'write'])}</small>←</button>)}</div></section><nav className="hub-tabs" aria-label={tx("بخش‌های یادگیری")}>{[['map','نقشهٔ دانش'],['projects','پروژه‌های واقعی'],['rooms','اتاق‌های دانش'],['library','کتابخانه'],['review','مرور و نقاط ضعف']].map(([id,label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => id==='library' ? readChapter(reading) : setTab(id!)}>{tx(label)}</button>)}</nav>
  {tab === 'map' && <><p className="hub-note">{tx("تسـلط یعنی حل یک تمرین تازه بدون راهنما. رنگ‌ها از نتیجهٔ تمرین‌های واقعی تو می‌آیند.")}</p><div className="skill-grid">{skills.map(s => { const status = getSkillStatus(progress,s.id); return <button key={s.id} className={`skill-card ${status}`} onClick={() => readChapter(s.chapterId)}><span className="skill-status-dot"/><b>{tx(s.title)}</b><small>{tx(skillLabels[status])}</small><span className="skill-dependencies">{tx("پیش‌نیاز: ")}{tx(s.prerequisites.map(id => skills.find(x => x.id === id)?.title).join('، ') || 'شروع مسیر')}</span></button>; })}</div><h2 className="hub-section-title">{tx("فصل‌های آموزش")}</h2><div className="chapter-grid">{chapters.map(c => { const target = entry(c.id), all = challenges.filter(x => x.chapterId === c.id), done = all.filter(x => progress.completedLessons.includes(x.id)); return <article className="chapter-card" key={c.id}><span className="chapter-index" dir="ltr">{tx(String(c.id).padStart(2,'0'))}</span><h3>{tx(c.title)}</h3><p>{tx(c.description)}</p><div className="chapter-progress"><i style={{width:`${done.length/all.length*100}%`}}/></div><small>{tx(done.length)}/{tx(all.length)}{tx(" تمرین")}</small><button onClick={() => readChapter(c.id)}>{tx("یادگیری مفهوم")}</button><button disabled={!target} onClick={() => target && open(target)}>{tx(target ? 'درس و تمرین ←' : 'پیش‌نیاز را کامل کن')}</button></article>; })}</div></>}
  {tab === 'projects' && <div className="project-grid">{projectDefinitions.map(p => <article className="project-card" key={p.id}><span className="eyebrow">BUILD A REAL THING</span><h2 dir="ltr">{tx(p.title)}</h2><p>{tx(p.description)}</p><ol>{challenges.filter(c => c.project?.id === p.id).sort((a,b)=>a.project!.step-b.project!.step).map(c => <li key={c.id}><button disabled={!isChallengeAvailable(c,progress.completedLessons)} onClick={() => open(c)}><span>{tx(progress.completedLessons.includes(c.id) ? '✓' : c.project?.step)}</span>{tx(c.title)}</button></li>)}</ol><small>{tx("کد هر مأموریت از آخرین نسخهٔ کامل‌شدهٔ خودت ادامه می‌یابد.")}</small></article>)}</div>}
  {tab === 'rooms' && <div className="rooms-grid">{rooms.map(r => { const available = isRoomAvailable(progress,r.id); return <article className={`knowledge-room ${available ? '' : 'locked'}`} style={{borderTopColor:r.color}} key={r.id}><span dir="ltr" className="room-emblem">{tx(r.emblem)}</span><h2>{tx(r.title)}</h2><p>{tx(r.subtitle)}</p><small>{tx(available ? 'آمادهٔ ورود' : `نیاز به تسلط: ${r.mastery.map(s => skills.find(x=>x.id===s)?.title).join('، ')}`)}</small><button disabled={!available} onClick={()=>onVisit(r.id)}>{tx(progress.selectedRoom===r.id?'در این اتاق هستی':'ورود به اتاق ←')}</button></article>; })}</div>}
  {tab === 'library' && <div className="library-layout"><nav>{chapters.map(c => <button key={c.id} className={reading===c.id?'active':''} onClick={()=>readChapter(c.id)}>{tx(c.id)}. {tx(c.title)}</button>)}</nav><article><div className="library-teaching"><h2>{tx(chapter.title)}</h2>{chapter.steps.map(step=><section key={step.id}><h3>{tx(step.title)}</h3><TeachingStepContent step={step}/></section>)}<a href={chapter.reference} target="_blank" rel="noreferrer">{tx("منبع و مطالعهٔ بیشتر ↗")}</a></div><button className="hub-primary" disabled={!entry(reading)} onClick={()=>{const c=entry(reading);if(c){open(c);}}}>{tx("ادامهٔ درس و سپس تمرین ←")}</button></article></div>}
  {tab === 'review' && <div className="review-layout"><article><h2>{tx("مرور فاصله‌دار")}</h2><p>{tx("تمرین پس از ۳ روز و گواه تسلط پس از ۱۴ روز برای مرور پیشنهاد می‌شود؛ وضعیت تسلط حفظ می‌شود.")}</p>{due.length ? due.map(c=><button key={c.id} onClick={()=>open(c)}>{tx(c.title)} ←</button>) : <p>{tx("مرور سررسیدشده‌ای نداری.")}</p>}</article><article><h2>{tx("موضوع‌هایی که نیاز به تمرین دارند")}</h2>{skills.filter(s=>progress.attempts.some(a=>a.failed.length && challenges.find(c=>c.id===a.id)?.skills?.includes(s.id) && !progress.completedLessons.includes(a.id))).map(s=><p key={s.id}>{tx(s.title)}{tx(" · تمرین مجدد در پیشنهادها")}</p>)}<h3>{tx("آخرین تلاش‌ها")}</h3>{progress.attempts.slice(-8).reverse().map((a,i)=><p key={`${a.at}-${i}`}>{tx(challenges.find(c=>c.id===a.id)?.title)} · {tx(a.failed.length ? `${a.failed.length} بررسی نیاز به اصلاح` : 'موفق')}</p>)}</article></div>}
  </div></section>;
}
