import type { Challenge, TestStep } from '@react-quest/shared';
import { buildProjects } from './builds';
import { contentHelpers as h, todoCode } from './content';
const { lesson, quiz, q, t, text, click, input, count } = h;

const intervalSolution = 'import {useState,useEffect} from "react";\nexport default function App(){const[count,setCount]=useState(0);useEffect(()=>{const id=setInterval(()=>setCount(n=>n+1),1000);return()=>clearInterval(id);},[]);return <output>{count}</output>; }';
const greetingSolution = 'import {useEffect,useState} from "react";\nexport function Greeting({name}){const[greeting,setGreeting]=useState("");useEffect(()=>setGreeting(`Hello ${name}`),[name]);return <output>{greeting}</output>;}\nexport default function App(){return <Greeting name="Ada" />;}';
const weatherCode = (step: number) => `import {useEffect,useState} from "react";
export function Weather({city}) {
 const [data,setData]=useState(null), [error,setError]=useState(false);
 useEffect(()=>{const controller=new AbortController();setData(null);setError(false);fetch("/api/weather?city="+city,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error("HTTP");return r.json();}).then(setData).catch(e=>{if(e.name!=="AbortError")setError(true);});return()=>controller.abort();},[city]);
 return <output>{error ? "Unavailable" : data ? data.city+" "+data.temperature+"°C" : "Loading"}</output>;
}
export default function App(){${step >= 3 ? 'const[city,setCity]=useState("Tehran"); return <main><select aria-label="City" value={city} onChange={e=>setCity(e.target.value)}><option>Tehran</option><option>Shiraz</option><option>Error</option></select><Weather city={city} /></main>;' : 'return <Weather city="Tehran" />;'}}`;
const movieCode = (debounced: boolean) => `import {useEffect,useState} from "react";
${debounced ? 'export function useDebounced(value){const[v,setV]=useState(value);useEffect(()=>{const id=setTimeout(()=>setV(value),300);return()=>clearTimeout(id);},[value]);return v;}' : ''}
export default function App(){const[query,setQuery]=useState(""),[movies,setMovies]=useState([]);${debounced ? 'const term=useDebounced(query);' : 'const term=query;'}useEffect(()=>{const c=new AbortController();if(!term){setMovies([]);return;}fetch("/api/movies?q="+term,{signal:c.signal}).then(r=>r.json()).then(setMovies).catch(()=>{});return()=>c.abort();},[term]);return <main><input aria-label="Movie" value={query} onChange={e=>setQuery(e.target.value)}/><ul>{movies.map(m=><li key={m.id}>{m.title}</li>)}</ul></main>;}`;
const shopCode = (step: number) => `import {useReducer,useState} from "react";
const products=[{id:1,name:"Keyboard",price:49},{id:2,name:"Mouse",price:29}];
export function cartReducer(state,action){if(action.type==="add")return {...state,[action.id]:(state[action.id]||0)+1};if(action.type==="remove")return {...state,[action.id]:Math.max(0,(state[action.id]||0)-1)};return state;}
export function Product({product,dispatch}){return <article><h2>{product.name}</h2><p>{product.price}</p>${step >= 2 ? '<button data-add={product.id} onClick={()=>dispatch({type:"add",id:product.id})}>Add</button><button data-remove={product.id} onClick={()=>dispatch({type:"remove",id:product.id})}>Remove</button>' : ''}</article>;}
export default function App(){const[cart,dispatch]=useReducer(cartReducer,{});const[expensive,setExpensive]=useState(false);const visible=products.filter(p=>!expensive||p.price>30);const total=products.reduce((sum,p)=>sum+p.price*(cart[p.id]||0),0);return <main>${step >= 3 ? '<label><input type="checkbox" aria-label="Premium" checked={expensive} onChange={e=>setExpensive(e.target.checked)} />Premium</label>' : ''}{visible.map(p=><Product key={p.id} product={p} dispatch={dispatch}/>)}<output>{total}</output></main>;}`;
const adminCode = (step: number) => `import {useState,useEffect} from "react";
export function UserRow({user,role,remove}){return <li><span>{user.name}</span>${step > 1 ? '<button disabled={role!=="Admin"} onClick={()=>remove(user.id)}>Delete</button>' : ''}</li>;}
export default function App(){const[users,setUsers]=useState([]),[role,setRole]=useState("Reader");useEffect(()=>{fetch("/api/users").then(r=>r.json()).then(setUsers);},[]);return <main>${step > 1 ? '<select aria-label="Role" value={role} onChange={e=>setRole(e.target.value)}><option>Reader</option><option>Admin</option></select>' : ''}<ul>{users.map(u=><UserRow key={u.id} user={u} role={role} remove={id=>setUsers(items=>items.filter(x=>x.id!==id))}/>)}</ul></main>;}`;

export const hooksBossSolution = `import {useState,useEffect,useRef} from "react";
export function Counter(){const[n,setN]=useState(0);useEffect(()=>{const id=setInterval(()=>setN(v=>v+1),1000);return()=>clearInterval(id);},[]);return <section><output data-count>{n}</output><button data-count-add onClick={()=>setN(v=>v+1)}>+1</button></section>;}
export function DependencyDemo({name}){const[value,setValue]=useState("");useEffect(()=>setValue("Hello "+name),[name]);return <p data-greeting>{value}</p>;}
export function ImmutableList(){const[items,setItems]=useState(["React"]);return <section><ul>{items.map(x=><li key={x}>{x}</li>)}</ul><button data-add onClick={()=>setItems(v=>[...v,"Hooks"])}>Add</button></section>;}
export function Fetcher({url}){const[value,setValue]=useState("Loading");useEffect(()=>{const c=new AbortController();fetch(url,{signal:c.signal}).then(r=>{if(!r.ok)throw Error("HTTP");return r.json();}).then(()=>setValue("Loaded")).catch(e=>{if(e.name!=="AbortError")setValue("Unavailable");});return()=>c.abort();},[url]);return <p data-status>{value}</p>;}
export function FocusField(){const ref=useRef(null);return <section><input data-focus ref={ref}/><button data-focus-button onClick={()=>ref.current.focus()}>Focus</button></section>;}
export default function App(){return <main><Counter/><DependencyDemo name="Ada"/><ImmutableList/><Fetcher url="/api/users"/><FocusField/></main>;}`;
const bossStarter = hooksBossSolution
  .replace('()=>setN(v=>v+1),1000);return()=>clearInterval(id);},[]);', '()=>setN(n+1),1000);setN(n+1);},[n]);')
  .replace('onClick={()=>setN(v=>v+1)}', 'onClick={()=>{ n++; }}')
  .replace('const[n,setN]', 'let[n,setN]')
  .replace('[name]);', '[]);')
  .replace('()=>setItems(v=>[...v,"Hooks"])', '()=>{items.push("Hooks");setItems(items);}')
  .replace('if(!r.ok)throw Error("HTTP");', '')
  .replace('()=>ref.current.focus()', '()=>ref.focus()');

const querySolution = `import {QueryClient,QueryClientProvider,useQuery,useQueryClient} from "@tanstack/react-query";
const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
export function Weather(){const q=useQuery({queryKey:["weather","Tehran"],queryFn:()=>fetch("/api/weather?city=Tehran").then(r=>r.json()),staleTime:60000});const c=useQueryClient();return <main><output>{q.isPending?"Loading":q.isError?"Unavailable":q.data.city+" "+q.data.temperature+"°C"}</output><button onClick={()=>c.setQueryData(["weather","Tehran"],{city:"Tehran",temperature:25})}>Update cache</button></main>;}
export default function App(){return <QueryClientProvider client={client}><Weather/></QueryClientProvider>;}`;
const reduxSolution = `import {configureStore,createSlice} from "@reduxjs/toolkit";
import {Provider,useDispatch,useSelector} from "react-redux";
const slice=createSlice({name:"counter",initialState:{value:0},reducers:{increment:state=>{state.value++;},reset:state=>{state.value=0;}}});
const store=configureStore({reducer:{counter:slice.reducer}});
export function Counter(){const value=useSelector(s=>s.counter.value);const dispatch=useDispatch();return <main><output>{value}</output><button onClick={()=>dispatch(slice.actions.increment())}>Add</button><button onClick={()=>dispatch(slice.actions.reset())}>Reset</button></main>;}
export default function App(){return <Provider store={store}><Counter/></Provider>;}`;
const routesSolution = `import {MemoryRouter,Routes,Route,Link,Outlet} from "react-router-dom";
function Layout(){return <main><nav><Link to="/">Home</Link><Link to="/help">Help</Link></nav><Outlet/></main>;}
export default function App(){return <MemoryRouter><Routes><Route path="/" element={<Layout/>}><Route index element={<h1>Home page</h1>}/><Route path="help" element={<h1>Help page</h1>}/></Route></Routes></MemoryRouter>;}`;
const testingSolution = `import {useState} from "react";
export default function App(){const[n,setN]=useState(0);return <main><output role="status">{n}</output><button onClick={()=>setN(v=>v+1)}>+1</button></main>;}
export async function testCounter({render,screen,fireEvent,expect}){render(<App/>);expect(screen.getByRole("status")).toHaveTextContent("0");fireEvent.click(screen.getByRole("button",{name:"+1"}));expect(screen.getByRole("status")).toHaveTextContent("1");}`;
const finalSolution = todoCode(8)
  .replace(/const initialTodos = .*;/, 'const initialTodos = [];')
  .replace('const { visible, draft', 'const { todos, visible, draft')
  .replace('<h1>My Tasks</h1>', '<h1>Study Planner</h1>')
  .replace('</main>;', '<output aria-label="Completed">{todos.filter(t=>t.done).length}</output></main>;');

export const advancedChallenges: Challenge[] = [
  lesson({ id: 'effect-greeting', chapterId: 6, title: 'Dependency درست', kind: 'debug', skills: ['effects'], tags: ['dependencies'], description: 'وقتی prop تغییر می‌کند، نتیجهٔ همگام‌سازی نباید قدیمی بماند.', instructions: ['Greeting({name}) را export کن و output برابر Hello name بساز.', 'تغییر name بدون unmount هم باید نتیجه را عوض کند.', 'این مثال برای تمرین dependency است؛ برای صرفاً ساخت greeting معمولاً Effect لازم نیست.'], starter: greetingSolution.replace('[name]', '[]'), solution: greetingSolution, tests: [t('deps', 'پاسخ به prop تازه در همان نمونه', [{ type: 'render', component: 'Greeting', props: { name: 'Ada' } }, text('output', 'Hello Ada'), { type: 'rerender', component: 'Greeting', props: { name: 'Grace' } }, text('output', 'Hello Grace')], { hook: 'useEffect' })] }),
  lesson({ id: 'interval-debug', chapterId: 6, title: 'یک interval، دو باگ', kind: 'debug', skills: ['effects'], tags: ['cleanup', 'closures'], prerequisites: ['effect-greeting'], description: 'snapshot قدیمی و interval رهاشده را پیدا کن.', instructions: ['output از 0 شروع شود؛ interval هر ۱۰۰۰ میلی‌ثانیه یک واحد اضافه کند.', 'دو tick باید 2 بسازد و unmount هیچ interval فعالی باقی نگذارد.'], starter: intervalSolution.replace('setCount(n=>n+1)', 'setCount(count+1)').replace('return()=>clearInterval(id);', ''), solution: intervalSolution, tests: [t('ticks', 'دو tick با مقدار تازه', [{ type: 'clock', milliseconds: 2000 }, text('output', '2')], { hook: 'useEffect' }), t('cleanup', 'منبع پس از unmount آزاد می‌شود', [{ type: 'unmount' }, { type: 'timer-count', count: 0 }])] }),
  quiz('closure-predict', 6, 'کدام snapshot در callback مانده؟', 'predict', [q('closure', 'interval با dependency خالی و setCount(count + 1) چه می‌کند؟', ['هر بار یک واحد بالا می‌رود', 'معمولاً روی ۱ می‌ماند', 'هیچ renderی ندارد'], 1, 'callback همان count صفر را از render اول بسته است؛ updater تابعی مقدار فعلی را دریافت می‌کند.', 'useEffect(() => { const id = setInterval(() => setCount(count + 1), 1000); return () => clearInterval(id); }, []);')], ['interval-debug']),
  lesson({ id: 'effects-mastery', chapterId: 6, title: 'گواه تسلط: ساعت آزمایشگاه', mastery: true, skills: ['effects'], tags: ['cleanup', 'closures'], prerequisites: ['closure-predict'], description: 'یک مسئلهٔ مستقل برای اثبات تسلط cleanup.', instructions: ['output از 10 شروع شود و هر ثانیه یک واحد کم شود.', 'بعد از ۳ tick مقدار 7 باشد و هنگام unmount interval پاک شود.'], solution: intervalSolution.replace('useState(0)', 'useState(10)').replace('n=>n+1', 'n=>n-1'), tests: [t('clock', 'شمارش معکوس مستقل', [{ type: 'clock', milliseconds: 3000 }, text('output', '7')], { hook: 'useEffect' }), t('cleanup', 'cleanup آزمون تازه', [{ type: 'unmount' }, { type: 'timer-count', count: 0 }])] }),
  lesson({ id: 'ref-focus', chapterId: 6, title: 'Refs برای فوکوس', skills: ['refs'], mastery: true, prerequisites: ['effect-greeting'], description: 'بدون state اضافه، روی ورودی فوکوس کن.', instructions: ['یک input و button متن Focus بساز.', 'با useRef و رویداد کلیک، input فعال شود.'], solution: 'import {useRef} from "react";\nexport default function App(){const ref=useRef(null);return <main><input ref={ref}/><button onClick={()=>ref.current.focus()}>Focus</button></main>;}', tests: [t('focus', 'فوکوس واقعی DOM', [click('button'), { type: 'focus', selector: 'input' }], { hook: 'useRef' })] }),
  lesson({ id: 'hooks-boss', chapterId: 6, title: 'HOOKS BOSS — هفت باگ', kind: 'boss', skills: ['effects', 'state', 'refs'], tags: ['cleanup', 'dependencies', 'closures', 'mutation'], xp: 300, difficulty: 5, minutes: 25, prerequisites: ['interval-debug', 'ref-focus'], description: 'یک برنامهٔ خراب را به یک برنامهٔ قابل اعتماد تبدیل کن. هر تست موفق، یک بخش از HP را کم می‌کند.', instructions: ['ابتدا حلقهٔ Effect را متوقف کن؛ Counter از 0 شروع شود.', 'setter کلیک، updater interval و cleanup آن را درست کن.', 'DependencyDemo باید به تغییر name، ImmutableList به افزودن، Fetcher به خطای HTTP و FocusField به فوکوس پاسخ دهند.'], starter: bossStarter, solution: hooksBossSolution, tests: [t('state', '۱ · تغییر state با setter', [click('[data-count-add]'), text('[data-count]', '1')]), t('closure', '۲ · interval بدون حلقه و snapshot قدیمی', [{ type: 'clock', milliseconds: 2000 }, text('[data-count]', '2'), { type: 'effect-count', index: 1, max: 1 }]), t('cleanup', '۳ · cleanup interval', [{ type: 'unmount' }, { type: 'timer-count', count: 0 }]), t('deps', '۴ · dependency کامل', [{ type: 'render', component: 'DependencyDemo', props: { name: 'Ada' } }, { type: 'rerender', component: 'DependencyDemo', props: { name: 'Grace' } }, text('[data-greeting]', 'Hello Grace')]), t('mutation', '۵ · تغییر immutable لیست', [{ type: 'render', component: 'ImmutableList' }, click('[data-add]'), count('li', 2)]), t('http', '۶ · خطای HTTP', [{ type: 'render', component: 'Fetcher', props: { url: '/api/fail' } }, { type: 'wait-text', selector: '[data-status]', text: 'Unavailable' }]), t('ref', '۷ · دسترسی به current در Ref', [{ type: 'render', component: 'FocusField' }, click('[data-focus-button]'), { type: 'focus', selector: '[data-focus]' }])] }),
  ...[1, 2, 3].map(step => lesson({ id: ['fetch-weather', 'weather-error', 'api-mastery'][step - 1]!, chapterId: 7, title: ['Weather ۱: دریافت و loading', 'Weather ۲: نمایش خطا', 'Weather ۳: شهر تازه'][step - 1]!, kind: 'feature', project: { id: 'weather', step }, mastery: step === 3, skills: ['api'], tags: ['async', 'cleanup'], prerequisites: [step === 1 ? 'effect-greeting' : ['fetch-weather', 'weather-error'][step - 2]!], description: 'داشبورد آب‌وهوا روی API آزمایشگاه؛ شبکهٔ واقعی یا کلید شخصی نیاز ندارد.', instructions: ['Weather({city}) را export کن.', 'output در حال دریافت Loading و سپس برای Tehran برابر Tehran 24°C باشد.', ...(step >= 2 ? ['city برابر Error باید Unavailable بدهد؛ status پاسخ را بررسی کن.'] : []), ...(step === 3 ? ['App یک select با aria-label="City" و گزینه‌های Tehran، Shiraz و Error داشته باشد.', 'تغییر شهر به Shiraz خروجی Shiraz 30°C بسازد؛ درخواست قبلی نباید نتیجهٔ تازه را خراب کند.'] : [])], starter: step === 1 ? 'import {useEffect,useState} from "react";\nexport function Weather({city}){return <output>Loading</output>;}\nexport default function App(){return <Weather city="Tehran"/>;}' : weatherCode(step - 1), solution: weatherCode(step), tests: [t('fetch', 'دریافت دادهٔ آزمایشگاه', [{ type: 'wait-text', selector: 'output', text: 'Tehran 24°C' }], { hook: 'useEffect' }), ...(step >= 2 ? [t('error', 'مسیر خطا هم تست می‌شود', [{ type: 'render', component: 'Weather', props: { city: 'Error' } }, { type: 'wait-text', selector: 'output', text: 'Unavailable' }])] : []), ...(step === 3 ? [t('city', 'دادهٔ ورودی تازه', [input('select', 'Shiraz'), { type: 'wait-text', selector: 'output', text: 'Shiraz 30°C' }])] : [])] })),
  ...[1, 2].map(step => lesson({ id: step === 1 ? 'movie-search' : 'debounced-search', chapterId: 7, title: step === 1 ? 'Movie Search: جست‌وجو' : 'Movie Search: Debounce', kind: 'feature', project: { id: 'movies', step }, skills: ['api', 'custom-hooks'], mastery: step === 2, prerequisites: [step === 1 ? 'fetch-weather' : 'movie-search'], description: 'به‌جای درخواست در هر render، تغییر ورودی و عمر درخواست را کنترل کن.', instructions: ['input با aria-label="Movie" بساز.', 'پس از ورود react دو li با React Story و State Wars نمایش بده.', ...(step === 2 ? ['useDebounced را export کن و پس از ۳۰۰ میلی‌ثانیه مقدار تازه را تحویل بده؛ timeout قبلی cleanup شود.'] : [])], starter: step === 1 ? undefined : movieCode(false), solution: movieCode(step === 2), tests: [t('search', 'نتیجهٔ جست‌وجوی واقعی Promise', [input('input', 'react'), { type: 'wait-text', selector: 'li:first-child', text: 'React Story', timeout: 1500 }, count('li', 2), input('input', 'hooks'), { type: 'wait-text', selector: 'li:first-child', text: 'Hooks Lab', timeout: 1500 }, count('li', 1)], step === 2 ? { function: 'useDebounced', hook: 'useEffect' } : undefined)] })),
  lesson({ id: 'routing-nested', chapterId: 8, title: 'مسیرهای تودرتو', kind: 'complete', skills: ['routing'], mastery: true, description: 'layout ثابت بماند و محتوای صفحه با مسیر تغییر کند.', instructions: ['از MemoryRouter، Routes، Route، Link و Outlet استفاده کن.', 'Linkهای Home و Help و h1های Home page و Help page داشته باش.', 'Help یک مسیر فرزند در layout مشترک باشد.'], starter: routesSolution.replace('<Outlet/>', ''), solution: routesSolution, tests: [t('routes', 'جابه‌جایی بدون از دست رفتن navigation', [text('h1', 'Home page'), click('a[href="/help"]'), text('h1', 'Help page'), count('nav a', 2), click('a[href="/"]'), text('h1', 'Home page')])] }),
  lesson({ id: 'reducer-counter', chapterId: 9, title: 'رویداد به Reducer', kind: 'complete', skills: ['reducer'], description: 'دو action را به تغییر خالص state وصل کن.', instructions: ['از useReducer استفاده کن؛ output از 0 شروع شود.', 'buttonهای Add و Reset، actionهای add و reset بفرستند.'], solution: 'import {useReducer} from "react";\nexport function reducer(state,action){return action.type==="add"?state+1:action.type==="reset"?0:state;}\nexport default function App(){const[n,dispatch]=useReducer(reducer,0);return <main><output>{n}</output><button onClick={()=>dispatch({type:"add"})}>Add</button><button onClick={()=>dispatch({type:"reset"})}>Reset</button></main>;}', tests: [t('actions', 'سه action سپس reset', [click('button:first-of-type', 3), text('output', '3'), click('button:last-of-type'), text('output', '0')], { hook: 'useReducer' })] }),
  lesson({ id: 'redux-mastery', chapterId: 9, title: 'گواه تسلط: Store مشترک', kind: 'feature', skills: ['reducer'], mastery: true, prerequisites: ['reducer-counter'], description: 'از Redux Toolkit و React Redux واقعی استفاده کن.', instructions: ['store را با configureStore و createSlice بساز و App را با Provider بپوشان.', 'Counter از useSelector و useDispatch استفاده کند.', 'output از 0 شروع و Add دو بار مقدار 2، سپس Reset مقدار 0 بسازد.'], solution: reduxSolution, tests: [t('store', 'Action → Reducer → Store → UI', [text('output', '0'), click('button:first-of-type', 2), text('output', '2'), click('button:last-of-type'), text('output', '0')], { component: 'Counter' })] }),
  lesson({ id: 'query-cache', chapterId: 10, title: 'Cache را در عمل ببین', kind: 'complete', skills: ['query'], mastery: true, description: 'useQuery واقعی و تغییر cache بدون درخواست جدید.', instructions: ['Weather را در QueryClientProvider نشان بده و useQuery برای /api/weather?city=Tehran اجرا کن.', 'output بعد از دریافت برابر Tehran 24°C باشد.', 'button متن Update cache با setQueryData دما را به 25 تغییر دهد.'], solution: querySolution, tests: [t('cache', 'دریافت و به‌روزرسانی cache', [{ type: 'wait-text', selector: 'output', text: 'Tehran 24°C' }, click('button'), { type: 'wait-text', selector: 'output', text: 'Tehran 25°C' }])] }),
  quiz('memo-reading', 11, 'کِی memo لازم نیست؟', 'read', [q('cheap', 'برای a + b با دو عدد کوچک، انتخاب پیش‌فرض چیست؟', ['useMemo همیشه', 'محاسبهٔ مستقیم', 'ذخیرهٔ نتیجه در Effect'], 1, 'هزینهٔ cache و پیچیدگی dependency معمولاً برای یک جمع ساده توجیه ندارد.'), q('different', 'تفاوت React.memo و useMemo چیست؟', ['یکی است', 'memo برای رد کردن render با props یکسان؛ useMemo برای cache مقدار', 'useMemo فقط برای شبکه است'], 1, 'هر ابزار هویت متفاوتی را بهینه می‌کند؛ رفتار صحیح برنامه نباید به حفظ cache وابسته باشد.')], ['state-counter']),
  lesson({ id: 'performance-mastery', chapterId: 11, title: 'گواه تسلط: دادهٔ مشتق‌شده', kind: 'refactor', mastery: true, skills: ['performance'], prerequisites: ['memo-reading'], description: 'Effect غیرضروری را حذف کن و dependency محاسبه را کامل نگه دار.', instructions: ['input aria-label="Search" برای فیلتر React و Redux و Vue بساز.', 'خروجی liها مستقیماً از term و آرایه مشتق شود؛ useEffect استفاده نکن.', 'جست‌وجوی Re باید دو نتیجه و Vue یک نتیجه بسازد.'], solution: 'import {useState} from "react";\nexport default function App(){const[term,setTerm]=useState("");const items=["React","Redux","Vue"].filter(x=>x.includes(term));return <main><input aria-label="Search" value={term} onChange={e=>setTerm(e.target.value)}/><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></main>;}', tests: [t('derived', 'نتیجه از ورودی فعلی مشتق می‌شود', [input('input', 'Re'), count('li', 2), input('input', 'Vue'), text('li', 'Vue'), count('li', 1)], { forbidHooks: ['useEffect'] })] }),
  lesson({ id: 'testing-mastery', chapterId: 12, title: 'تستی که باگ را می‌گیرد', mastery: true, skills: ['testing'], description: 'تستت هم روی نسخهٔ سالم و هم نسخهٔ خراب اجرا می‌شود.', instructions: ['App سالم آماده است؛ فقط export async function testCounter({render,screen,fireEvent,expect}) را کامل کن.', 'render(<App />)، مقدار اولیه و مقدار پس از کلیک را با Testing Library بررسی کن.', 'حداقل دو assertion داشته باش. تست باید نسخهٔ سالم را قبول و نسخهٔ بدون به‌روزرسانی را رد کند.'], starter: testingSolution.slice(0, testingSolution.indexOf('export async')) + 'export async function testCounter({render,screen,fireEvent,expect}) {\n  // تست رفتار را بنویس\n}', solution: testingSolution, tests: [t('healthy', 'تست روی رابط سالم پاس می‌شود', [{ type: 'student-test', mutant: false }], { function: 'testCounter' }), t('mutant', 'تست نسخهٔ خراب را رد می‌کند', [{ type: 'student-test', mutant: true }])] }),
  lesson({ id: 'architecture-refactor', chapterId: 13, title: 'App کوچک، مسئولیت روشن', kind: 'refactor', mastery: true, skills: ['architecture'], prerequisites: ['todo-hook'], description: 'یک برنامهٔ واقعی را بدون تغییر رفتار بازآرایی کن.', instructions: ['TodoItem، TodoList و useTodos را export کن.', 'منطق تغییر و ذخیره در useTodos باشد؛ App حداکثر ۴۰ خط.', 'افزودن و ذخیرهٔ یک task باید مانند قبل کار کند.'], starter: todoCode(7), solution: todoCode(8), tests: [t('structure', 'مرز مسئولیت و رفتار حفظ شده', [input('input[aria-label="Task"]', 'Refactor'), click('button[data-action="add"]'), text('li:last-child span', 'Refactor'), { type: 'storage', key: 'todos', contains: 'Refactor' }], { components: ['TodoItem', 'TodoList'], function: 'useTodos', maxLines: { name: 'App', count: 40 } })] }),
  ...[1, 2, 3].map(step => lesson({ id: ['shop-catalog', 'shop-cart', 'shop-filter'][step - 1]!, chapterId: 9, title: ['فروشگاه ۱: کاتالوگ', 'فروشگاه ۲: سبد خرید', 'فروشگاه ۳: فیلتر'][step - 1]!, kind: 'feature', project: { id: 'shop', step }, skills: ['props', 'reducer'], prerequisites: [step === 1 ? 'product-props' : ['shop-catalog', 'shop-cart'][step - 2]!], description: 'یک فروشگاه کوچک با state محلی، reducer و جمع مشتق‌شده.', instructions: ['Product({product,dispatch}) را export کن؛ Keyboard با 49 و Mouse با 29 نمایش بده.', ...(step >= 2 ? ['useReducer و cartReducer را به سبد وصل کن. دکمه‌ها data-add / data-remove برابر id محصول داشته باشند.', 'output مجموع سبد را نمایش دهد؛ تعداد محصول منفی نشود.'] : []), ...(step === 3 ? ['checkbox با aria-label="Premium" محصولات بیشتر از 30 را نگه دارد؛ فیلتر سبد را پاک نکند.'] : [])], starter: step > 1 ? shopCode(step - 1) : undefined, solution: shopCode(step), tests: [t('catalog', 'محصول‌ها از داده render می‌شوند', [count('article', 2), text('article:first-of-type h2', 'Keyboard')], { component: 'Product' }), ...(step >= 2 ? [t('cart', 'جمع و کاهش سبد', [click('[data-add="1"]', 2), text('output', '98'), click('[data-remove="1"]', 4), text('output', '0')], { hook: 'useReducer', function: 'cartReducer' })] : []), ...(step === 3 ? [t('filter', 'فیلتر نمای کاتالوگ', [click('input'), count('article', 1), text('h2', 'Keyboard')])] : [])] })),
  ...[1, 2].map(step => lesson({ id: step === 1 ? 'admin-users' : 'admin-role', chapterId: 13, title: step === 1 ? 'Admin Panel: کاربران' : 'Admin Panel: نقش رابط', kind: 'feature', project: { id: 'admin', step }, skills: ['api', 'architecture'], prerequisites: [step === 1 ? 'fetch-weather' : 'admin-users'], description: 'جدول کاربران و رفتار نقش‌ها؛ این نقش‌ها تمرین رابط‌اند و جای مجوز سرور را نمی‌گیرند.', instructions: ['کاربران را از /api/users بخوان؛ Ada و Grace در li نمایش داده شوند.', 'UserRow را export کن.', ...(step === 2 ? ['select با aria-label="Role" و Reader/Admin بساز. Delete در Reader غیرفعال و در Admin فعال باشد.', 'حذف یک کاربر روی state immutable انجام شود.'] : [])], starter: step > 1 ? adminCode(1) : undefined, solution: adminCode(step), tests: [t('users', 'دریافت و کامپوننت عضو', [{ type: 'wait-text', selector: 'li:first-child span', text: 'Ada' }, count('li', 2)], { component: 'UserRow' }), ...(step === 2 ? [t('role', 'تعامل نقش در رابط', [{ type: 'wait-text', selector: 'li:first-child span', text: 'Ada' }, { type: 'attribute', selector: 'li:first-child button', name: 'disabled', value: '' }, input('select', 'Admin'), click('li:first-child button'), count('li', 1), text('li span', 'Grace')])] : [])] })),
  quiz('interview-memo', 11, 'مصاحبه: دلیل انتخاب ابزار', 'read', [q('callback', 'useCallback چه چیزی را cache می‌کند؟', ['نتیجهٔ فراخوانی تابع', 'هویت تابع', 'دادهٔ سرور'], 1, 'useCallback خود تابع را cache می‌کند؛ useMemo نتیجهٔ محاسبه را و memo مرز render را هدف می‌گیرد.'), q('first', 'پیش از اضافه‌کردن memoization چه می‌کنی؟', ['همهٔ تابع‌ها را wrap می‌کنم', 'با مشاهده و اندازه‌گیری گلوگاه را مشخص می‌کنم', 'تمام state را به Redux می‌برم'], 1, 'بهینه‌سازی باید مسئلهٔ مشاهده‌شده‌ای را حل کند؛ پیچیدگی بی‌دلیل می‌تواند نتیجهٔ معکوس بدهد.')], ['effects-mastery', 'components-mastery']),
  lesson({ id: 'final-project', chapterId: 14, title: 'پروژهٔ نهایی: Study Planner', kind: 'boss', mastery: true, skills: ['architecture', 'forms', 'lists', 'state'], xp: 400, difficulty: 5, minutes: 35, project: { id: 'final', step: 1 }, description: 'از صفحهٔ خالی شروع کن. برنامهٔ مدیریت یادگیری خودت را بساز.', instructions: ['عنوان h1 برابر Study Planner و لیست اولیه خالی باشد.', 'فرم Task، دکمهٔ data-action="add"، checkbox Complete task، دکمهٔ data-action="delete" و فیلتر all/active/done داشته باش.', 'TodoItem، TodoList و useTodos را استخراج و export کن؛ App حداکثر ۴۰ خط.', 'لیست در کلید todos ذخیره و بعد از remount بازیابی شود؛ output تعداد انجام‌شده‌ها را نشان دهد.'], solution: finalSolution, tests: [t('add', 'ساخت دو task از صفحهٔ خالی', [input('input[aria-label="Task"]', 'Read React'), click('[data-action="add"]'), input('input[aria-label="Task"]', 'Practice'), click('[data-action="add"]'), count('.todos li', 2), text('h1', 'Study Planner')], { components: ['TodoItem', 'TodoList'], function: 'useTodos', maxLines: { name: 'App', count: 40 } }), t('complete-filter', 'انجام‌شدن و فیلتر', [input('input[aria-label="Task"]', 'Read React'), click('[data-action="add"]'), click('li input'), text('output', '1'), input('select', 'done'), count('li', 1)]), t('persist', 'ذخیره و بازیابی', [input('input[aria-label="Task"]', 'Keep learning'), click('[data-action="add"]'), { type: 'storage', key: 'todos', contains: 'Keep learning' }, { type: 'remount' }, text('li span', 'Keep learning')]), t('delete', 'حذف task فقط یک بار', [input('input[aria-label="Task"]', 'Temporary'), click('[data-action="add"]'), click('[data-action="delete"]'), count('li', 0)])] })
];

export const projectDefinitions = [
  { id: 'profile', title: 'Profile Card', description: 'کارت، props و بازآرایی', chapterId: 2 },
  { id: 'todo', title: 'Todo App', description: 'هشت مأموریت از عضو تا custom hook', chapterId: 4 },
  { id: 'weather', title: 'Weather Dashboard', description: 'دریافت، خطا و شهر تازه', chapterId: 7 },
  { id: 'movies', title: 'Movie Search', description: 'جست‌وجو و debounce', chapterId: 7 },
  { id: 'shop', title: 'E-commerce', description: 'کاتالوگ، reducer سبد و فیلتر', chapterId: 9 },
  { id: 'admin', title: 'Admin Panel', description: 'کاربران و نقش رابط', chapterId: 13 },
  { id: 'final', title: 'Study Planner', description: 'برنامه از صفحهٔ خالی', chapterId: 14 },
  ...buildProjects
];
export const fixtureEndpoints = ['/api/weather?city=Tehran', '/api/weather?city=Shiraz', '/api/weather?city=Error', '/api/movies?q=react', '/api/movies?q=hooks', '/api/users', '/api/fail'];
export const exampleClockStep: TestStep = { type: 'clock', milliseconds: 2000 };
