import type { Challenge, ChallengeTest, KnowledgeQuestion, TestStep } from '@react-quest/shared';
import { chapters } from './curriculum';

const blank = 'export default function App() {\n  return <main>{/* رابط تو */}</main>;\n}\n';
const t = (id: string, name: string, steps: TestStep[], source?: ChallengeTest['source']): ChallengeTest => ({ id, name, steps, source, mandatory: true });
const text = (selector: string, value: string): TestStep => ({ type: 'text', selector, text: value });
const click = (selector: string, times = 1): TestStep => ({ type: 'click', selector, times });
const input = (selector: string, value: string): TestStep => ({ type: 'input', selector, value });
const count = (selector: string, value: number): TestStep => ({ type: 'count', selector, count: value });
type Lesson = Omit<Challenge, 'topic' | 'starterFiles' | 'hints' | 'xp' | 'coins' | 'prerequisites'> & { chapterId: number; starter?: string; hints?: string[]; prerequisites?: string[]; xp?: number; solution: string };
function lesson(data: Lesson): Challenge {
  const chapter = chapters.find(item => item.id === data.chapterId)!;
  const hints = [
    `به اولین نیازمندی نگاه کن: «${data.instructions[0]}»؛ کدام ورودی باید این خروجی را تعیین کند؟`,
    chapter.concept.paragraphs[0]!,
    `اول مقدار اولیه را نمایش بده، سپس فقط یک تعامل را پیاده کن. انتظار اولین بررسی: ${data.tests[0]?.name ?? 'رفتار خواسته‌شده'}.`,
    `نمونهٔ کوچک از همین مفهوم، برای تطبیق با مسئلهٔ تو:\n${chapter.concept.example}`
  ];
  return { topic: chapter.skills[0]!, skills: chapter.skills, concept: chapter.concept, kind: 'write', minutes: 8, difficulty: 2, coins: 10, xp: data.mastery ? 160 : 100, hints, prerequisites: chapter.prerequisites, ...data, starterFiles: { 'src/App.jsx': data.starter ?? blank } };
}
const q = (id: string, prompt: string, options: string[], answer: number, explanation: string, code?: string): KnowledgeQuestion => ({ id, prompt, options, answer, explanation, code });
function quiz(id: string, chapterId: number, title: string, kind: 'read' | 'predict', questions: KnowledgeQuestion[], prerequisites?: string[]): Challenge {
  return lesson({ id, chapterId, title, kind, description: 'پیش از اجرا، رفتار کد را تحلیل کن. پس از پاسخ، دلیل را مرور کن.', instructions: ['برای هر سؤال یک پاسخ انتخاب کن.', 'درست بودن نتیجه کافی نیست؛ توضیح پس از پاسخ را بخوان.'], questions, tests: questions.map(question => ({ id: question.id, name: question.prompt, mandatory: true, questionId: question.id, steps: [] })), solution: blank, prerequisites, xp: 60, minutes: 4 });
}

export function todoCode(step: number) {
  const logic = `const [todos, setTodos] = useState(${step >= 7 ? '() => JSON.parse(localStorage.getItem("todos") || "null") || initialTodos' : 'initialTodos'});
  const [draft, setDraft] = useState("");
  const [filter, setFilter] = useState("all");
  ${step >= 7 ? 'useEffect(() => localStorage.setItem("todos", JSON.stringify(todos)), [todos]);' : ''}
  function add(event) { event.preventDefault(); if (!draft.trim()) return; setTodos(items => [...items, { id: Date.now(), text: draft.trim(), done: false }]); setDraft(""); }
  function remove(id) { setTodos(items => items.filter(item => item.id !== id)); }
  function toggle(id) { setTodos(items => items.map(item => item.id === id ? { ...item, done: !item.done } : item)); }
  const visible = todos.filter(item => filter === "all" || (filter === "done" ? item.done : !item.done));`;
  const list = '<ul className="todos">{visible.map(todo => <TodoItem key={todo.id} todo={todo} remove={remove} toggle={toggle} />)}</ul>';
  return `import { useState, useEffect } from "react";
const initialTodos = [{ id: 1, text: "Learn React", done: false }, { id: 2, text: "Practice", done: false }];
export function TodoItem({ todo, remove, toggle }) {
  return <li data-done={String(todo.done)}><span>{todo.text}</span>${step >= 5 ? '<input type="checkbox" aria-label="Complete task" checked={todo.done} onChange={() => toggle(todo.id)} />' : ''}${step >= 4 ? '<button data-action="delete" onClick={() => remove(todo.id)}>Delete</button>' : ''}</li>;
}
${step >= 8 ? `export function useTodos() { ${logic}\n return { todos, visible, draft, setDraft, filter, setFilter, add, remove, toggle }; }
export function TodoList({ visible, remove, toggle }) { return ${list}; }` : ''}
export default function App() {
  ${step >= 8 ? 'const { visible, draft, setDraft, filter, setFilter, add, remove, toggle } = useTodos();' : step >= 2 ? logic : ''}
  return <main><h1>My Tasks</h1>
    ${step >= 3 ? '<form onSubmit={add}><input aria-label="Task" value={draft} onChange={e => setDraft(e.target.value)} /><button data-action="add">Add</button></form>' : ''}
    ${step >= 6 ? '<select aria-label="Filter" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All</option><option value="active">Active</option><option value="done">Done</option></select>' : ''}
    ${step >= 8 ? '<TodoList visible={visible} remove={remove} toggle={toggle} />' : step >= 2 ? list : '<ul className="todos"><TodoItem todo={initialTodos[0]} /></ul>'}
  </main>;
}`;
}

export const extraChallenges: Challenge[] = [
  quiz('js-map', 0, 'تبدیل داده با map', 'predict', [q('map', 'خروجی names چیست؟', ['["Ada", "Linus"]', '["Ada"]', '[true, false]', 'خطا'], 1, 'filter فقط کاربر active را نگه می‌دارد و map نام او را برمی‌گرداند.', 'const users = [{ name: "Ada", active: true }, { name: "Linus", active: false }];\nconst names = users.filter(u => u.active).map(u => u.name);')], []),
  lesson({ id: 'js-immutable', chapterId: 0, title: 'کپی بدون تغییر اصل', kind: 'complete', skills: ['javascript'], mastery: true, prerequisites: ['js-map'], description: 'یک تابع خالص برای اضافه‌کردن عضو به آرایه بساز.', instructions: ['addItem(items, item) را export کن و یک آرایهٔ جدید برگردان.', 'App خروجی addItem(["React"], "JS") را در دو li نشان دهد.', 'طول آرایهٔ اصلی را در output نشان بده؛ باید 1 باقی بماند.'], starter: 'export function addItem(items, item) { return items; }\nexport default function App() { const result = addItem(["React"], "JS"); return <ul>{result.map(x => <li key={x}>{x}</li>)}</ul>; }', solution: 'export function addItem(items, item) { return [...items, item]; }\nexport default function App() { const items = ["React"]; const result = addItem(items, "JS"); return <main><ul>{result.map(x => <li key={x}>{x}</li>)}</ul><output>{items.length}</output></main>; }', tests: [t('array', 'خروجی جدید و آرایهٔ اصلی', [count('li', 2), text('li:last-child', 'JS'), text('output', '1')], { function: 'addItem' })] }),
  quiz('jsx-reading', 1, 'خواندن JSX', 'read', [q('expression', 'کدام مقدار نمایش داده می‌شود؟', ['name', 'Ada', '{name}', 'هیچ چیز'], 1, 'آکولاد عبارت name را ارزیابی می‌کند؛ متن Ada وارد h1 می‌شود.', 'const name = "Ada";\nreturn <h1>{name}</h1>;')], ['hello-react']),
  lesson({ id: 'jsx-mastery', chapterId: 1, title: 'گواه تسلط: پیام پویا', skills: ['jsx'], mastery: true, prerequisites: ['jsx-reading'], description: 'یک نیازمندی تازه را بدون راهنمایی حل کن.', instructions: ['Greeting را export کن و prop به نام name دریافت کن.', 'در h1 متن Welcome Sara نمایش بده و App آن را با Sara استفاده کند.', 'برای name جدید هم درست کار کند.'], solution: 'export function Greeting({name}) { return <h1>Welcome {name}</h1>; }\nexport default function App() { return <Greeting name="Sara" />; }', tests: [t('greeting', 'نام جدید، پیام جدید', [{ type: 'render', component: 'Greeting', props: { name: 'Nima' } }, text('h1', 'Welcome Nima')], { component: 'Greeting' })] }),
  lesson({ id: 'panel-composition', chapterId: 2, title: 'یک قاب، چند محتوا', kind: 'complete', skills: ['components', 'props'], prerequisites: ['product-props'], description: 'قاب را از محتوای داخل آن جدا کن.', instructions: ['Panel را export کن و children را داخل section نمایش بده.', 'App دو Panel با عنوان‌های Profile و Skills داشته باشد.'], starter: 'export function Panel({children}) { return <section />; }\nexport default function App() { return <main><Panel><h2>Profile</h2></Panel><Panel><h2>Skills</h2></Panel></main>; }', solution: 'export function Panel({children}) { return <section>{children}</section>; }\nexport default function App() { return <main><Panel><h2>Profile</h2></Panel><Panel><h2>Skills</h2></Panel></main>; }', tests: [t('children', 'محتوای دو قاب مستقل', [count('section', 2), text('section:first-child h2', 'Profile'), text('section:last-child h2', 'Skills')], { component: 'Panel' })] }),
  lesson({ id: 'profile-refactor', chapterId: 2, title: 'بازآرایی کارت پروفایل', kind: 'refactor', skills: ['components', 'props'], project: { id: 'profile', step: 2 }, prerequisites: ['panel-composition'], description: 'تکرار کارت‌ها را با کامپوننت حذف کن؛ رفتار باید ثابت بماند.', instructions: ['ProfileCard({name, role}) را export کن.', 'App کارت‌های Ada / Developer و Grace / Engineer را نشان دهد.', 'App حداکثر ۱۲ خط و کارت با prop جدید هم قابل استفاده باشد.'], starter: 'export default function App() { return <main><article><h2>Ada</h2><p>Developer</p></article><article><h2>Grace</h2><p>Engineer</p></article></main>; }', solution: 'export function ProfileCard({name,role}) { return <article><h2>{name}</h2><p>{role}</p></article>; }\nexport default function App() { return <main><ProfileCard name="Ada" role="Developer" /><ProfileCard name="Grace" role="Engineer" /></main>; }', tests: [t('cards', 'رفتار قبلی حفظ شده', [count('article', 2), text('article:first-child h2', 'Ada'), text('article:last-child p', 'Engineer')]), t('extract', 'کامپوننت reusable و App کوچک', [{ type: 'render', component: 'ProfileCard', props: { name: 'Linus', role: 'Maintainer' } }, text('h2', 'Linus'), text('p', 'Maintainer')], { component: 'ProfileCard', maxLines: { name: 'App', count: 12 } })] }),
  lesson({ id: 'components-mastery', chapterId: 2, title: 'گواه تسلط: کارت تنظیمات', mastery: true, skills: ['components', 'props'], prerequisites: ['profile-refactor'], description: 'این کارت تازه، نشان تسلط کامپوننت و props است.', instructions: ['SettingsCard({title, enabled}) را export کن.', 'یک article با h2 عنوان و p برابر On یا Off بساز.', 'App عنوان Sound و enabled=false را استفاده کند.'], solution: 'export function SettingsCard({title,enabled}) { return <article><h2>{title}</h2><p>{enabled ? "On" : "Off"}</p></article>; }\nexport default function App() { return <SettingsCard title="Sound" enabled={false} />; }', tests: [t('on', 'Props جدید: On', [{ type: 'render', component: 'SettingsCard', props: { title: 'Music', enabled: true } }, text('h2', 'Music'), text('p', 'On')], { component: 'SettingsCard' }), t('off', 'Props جدید: Off', [{ type: 'render', component: 'SettingsCard', props: { title: 'Alerts', enabled: false } }, text('p', 'Off')])] }),
  quiz('state-batching', 3, 'دو درخواست، یک snapshot', 'predict', [q('snapshot', 'پس از یک کلیک چه عددی دیده می‌شود؟', ['0', '1', '2', 'خطا'], 1, 'هر دو setter مقدار ۱ را از snapshot صفر می‌سازند؛ updater تابعی برای دو افزایش مستقل مناسب است.', 'const [count, setCount] = useState(0);\nfunction handleClick() {\n  setCount(count + 1);\n  setCount(count + 1);\n}')], ['state-counter']),
  lesson({ id: 'state-debug', chapterId: 3, title: 'چرا شمارنده زنده نیست؟', kind: 'debug', skills: ['state', 'events'], prerequisites: ['state-batching'], description: 'هم علت اصلی را پیدا کن، هم رفتار را درست کن.', instructions: ['علت به‌روز نشدن رابط را انتخاب کن.', 'از state استفاده کن؛ output از 0 شروع و با دو کلیک به 2 برسد.'], questions: [q('root-cause', 'علت اصلی چیست؟', ['let در حافظه ذخیره نمی‌شود', 'تغییر متغیر معمولی render درخواست نمی‌کند', 'onClick همیشه اشتباه است'], 1, 'React از تغییر متغیر معمولی خبر ندارد؛ setter یک به‌روزرسانی state درخواست می‌کند.')], starter: 'export default function App() { let count = 0; return <main><output>{count}</output><button onClick={() => count++}>+1</button></main>; }', solution: 'import {useState} from "react";\nexport default function App() { const [count,setCount] = useState(0); return <main><output>{count}</output><button onClick={() => setCount(n => n + 1)}>+1</button></main>; }', tests: [{ id: 'cause', name: 'علت اصلی شناسایی شد', mandatory: true, questionId: 'root-cause', steps: [] }, t('fix', 'رفع باگ واقعی', [text('output', '0'), click('button', 2), text('output', '2')], { hook: 'useState' })] }),
  lesson({ id: 'state-toggle', chapterId: 3, title: 'ساخت Toggle', kind: 'feature', skills: ['state', 'events'], prerequisites: ['state-debug'], description: 'یک نیاز واقعی: روشن و خاموش کردن اعلان.', instructions: ['output ابتدا Off باشد.', 'button با متن Toggle وضعیت را به On و دوباره Off تغییر دهد.'], solution: 'import {useState} from "react";\nexport default function App() { const [enabled,setEnabled] = useState(false); return <main><output>{enabled ? "On" : "Off"}</output><button onClick={() => setEnabled(v => !v)}>Toggle</button></main>; }', tests: [t('toggle', 'دو بار تغییر وضعیت', [text('output', 'Off'), click('button'), text('output', 'On'), click('button'), text('output', 'Off')], { hook: 'useState' })] }),
  lesson({ id: 'quantity-mastery', chapterId: 3, title: 'گواه تسلط: تعداد سفارش', mastery: true, skills: ['state', 'events'], prerequisites: ['state-toggle'], description: 'مسئلهٔ تازه، بدون راهنمایی: تعداد سفارش از یک کمتر نشود.', instructions: ['output از 1 شروع شود.', 'دکمه‌های - و + بساز. کاهش در 1 ثابت بماند؛ افزایش و کاهش کار کند.'], solution: 'import {useState} from "react";\nexport default function App() { const [n,setN] = useState(1); return <main><output>{n}</output><button onClick={() => setN(v => Math.max(1,v-1))}>-</button><button onClick={() => setN(v => v+1)}>+</button></main>; }', tests: [t('minimum', 'مرز و انتقال state', [click('button:first-of-type', 2), text('output', '1'), click('button:last-of-type', 3), text('output', '4'), click('button:first-of-type'), text('output', '3')], { hook: 'useState' })] }),
  lesson({ id: 'thermostat-mastery', chapterId: 3, title: 'آزمون تازه: ترموستات', mastery: true, skills: ['state', 'events'], prerequisites: ['state-toggle'], description: 'اگر در آزمون قبل کمک گرفتی، این مسئلهٔ مستقل فرصت تازهٔ تسلط است.', instructions: ['output ابتدا 20 باشد؛ دکمه‌های Cool و Warm بساز.', 'دما با هر کلیک یک واحد تغییر کند ولی از 16 کمتر و از 24 بیشتر نشود.'], solution: 'import {useState} from "react";\nexport default function App(){const[n,setN]=useState(20);return <main><output>{n}</output><button onClick={()=>setN(v=>Math.max(16,v-1))}>Cool</button><button onClick={()=>setN(v=>Math.min(24,v+1))}>Warm</button></main>;}', tests: [t('bounds', 'کران‌های دمای تازه', [click('button:first-of-type', 7), text('output', '16'), click('button:last-of-type', 12), text('output', '24')], { hook: 'useState' })] }),
  ...['todo-item', 'todo-render', 'todo-add', 'todo-delete', 'todo-complete', 'todo-filter', 'todo-storage', 'todo-hook'].map((id, index) => lesson({ id, chapterId: index < 2 ? 4 : index < 7 ? 5 : 6, title: ['Todo ۱: یک عضو', 'Todo ۲: نمایش لیست', 'Todo ۳: افزودن', 'Todo ۴: حذف', 'Todo ۵: انجام‌شدن', 'Todo ۶: فیلتر', 'Todo ۷: ذخیره', 'Todo ۸: بازآرایی با Hook'][index]!, kind: index === 7 ? 'refactor' : index === 0 ? 'complete' : 'feature', project: { id: 'todo', step: index + 1 }, skills: index === 7 ? ['architecture', 'custom-hooks', 'lists'] : index < 2 ? ['lists', 'components'] : ['forms', 'lists', 'state'], mastery: index === 7, prerequisites: [index === 0 ? 'state-counter' : ['todo-item', 'todo-render', 'todo-add', 'todo-delete', 'todo-complete', 'todo-filter', 'todo-storage'][index - 1]!], description: 'یک پروژهٔ پیوسته: کد مرحلهٔ قبلی تو به مرحلهٔ بعد منتقل می‌شود.', instructions: [
    ['TodoItem({todo}) را export کن؛ text در span و عضو در li قرار گیرد.', 'App یک ul با className="todos" و یک TodoItem نشان دهد.'],
    ['دو کار اولیه Learn React و Practice را با key پایدار در .todos نمایش بده.'],
    ['فرم با input دارای aria-label="Task" و دکمهٔ data-action="add" بساز.', 'کار تازه به انتهای لیست اضافه و input خالی شود؛ ورودی خالی کار اضافه نکند.'],
    ['در هر عضو دکمهٔ data-action="delete" بساز؛ فقط همان عضو حذف شود.'],
    ['checkbox با aria-label="Complete task" اضافه کن.', 'li ویژگی data-done را به صورت رشتهٔ true یا false منعکس کند؛ تغییر immutable باشد.'],
    ['select دارای aria-label="Filter" با valueهای all، active، done بساز.', 'فیلتر فقط نمای لیست را عوض کند و دادهٔ اصلی باقی بماند.'],
    ['لیست را در کلید todos در localStorage تمرین ذخیره و هنگام mount بازیابی کن.'],
    ['TodoItem و TodoList را استخراج و export کن.', 'useTodos را export و منطق state/ذخیره را به آن منتقل کن.', 'App حداکثر ۴۰ خط باشد؛ رفتار افزودن، فیلتر و ذخیره حفظ شود.']
  ][index]!, starter: index === 0 ? 'export function TodoItem({todo}) { return <li />; }\nexport default function App(){return <ul className="todos"><TodoItem todo={{id:1,text:"Learn React",done:false}} /></ul>;}' : todoCode(index), solution: todoCode(index + 1), tests: [
    t('behavior', 'رفتار این مرحله از پروژه', index === 0 ? [text('li span', 'Learn React')] : index === 1 ? [count('.todos li', 2), text('li:first-child span', 'Learn React')] : index === 2 ? [input('input[aria-label="Task"]', 'Build'), click('button[data-action="add"]'), count('.todos li', 3), text('li:last-child span', 'Build')] : index === 3 ? [click('li:first-child button[data-action="delete"]'), count('.todos li', 1), text('li span', 'Practice')] : index === 4 ? [click('li:first-child input'), { type: 'attribute', selector: 'li:first-child', name: 'data-done', value: 'true' }] : index === 5 ? [click('li:first-child input'), input('select', 'done'), count('.todos li', 1), text('li span', 'Learn React'), input('select', 'all'), count('.todos li', 2)] : [input('input[aria-label="Task"]', 'Saved'), click('button[data-action="add"]'), { type: 'storage', key: 'todos', contains: 'Saved' }, { type: 'remount' }, text('li:last-child span', 'Saved')], index === 7 ? { components: ['TodoItem', 'TodoList'], hook: 'useState', function: 'useTodos', maxLines: { name: 'App', count: 40 } } : { component: 'TodoItem' })
  ] })),
  lesson({ id: 'form-name', chapterId: 5, title: 'فرم کنترل‌شده', skills: ['forms'], prerequisites: ['todo-render'], description: 'یک نام را از ورودی بخوان و هم‌زمان نمایش بده.', instructions: ['input با aria-label="Name" را به state وصل کن.', 'output ابتدا Anonymous و پس از ورود Ada برابر Hello Ada باشد.', 'input خالی دوباره Anonymous نمایش دهد.'], solution: 'import {useState} from "react";\nexport default function App(){const[name,setName]=useState("");return <main><input aria-label="Name" value={name} onChange={e=>setName(e.target.value)} /><output>{name ? `Hello ${name}` : "Anonymous"}</output></main>;}', tests: [t('controlled', 'ورودی و خروجی همگام', [text('output', 'Anonymous'), input('input', 'Ada'), text('output', 'Hello Ada'), input('input', ''), text('output', 'Anonymous')], { hook: 'useState' })] }),
  lesson({ id: 'forms-mastery', chapterId: 5, title: 'گواه تسلط: ثبت ایمیل', mastery: true, skills: ['forms'], prerequisites: ['form-name'], description: 'اعتبارسنجی و submit واقعی.', instructions: ['فرم با input aria-label="Email" و button متن Save بساز.', 'output ابتدا Empty باشد. submit فاقد @ برابر Invalid و ایمیل معتبر برابر Saved شود.', 'submit نباید صفحه را reload کند.'], solution: 'import {useState} from "react";\nexport default function App(){const[email,setEmail]=useState("");const[status,setStatus]=useState("Empty");return <form onSubmit={e=>{e.preventDefault();setStatus(email.includes("@")?"Saved":"Invalid");}}><input aria-label="Email" value={email} onChange={e=>setEmail(e.target.value)} /><button>Save</button><output>{status}</output></form>;}', tests: [t('validate', 'نامعتبر سپس معتبر', [input('input', 'ada'), click('button'), text('output', 'Invalid'), input('input', 'ada@example.com'), click('button'), text('output', 'Saved')])] }),
  quiz('login-reading', 3, 'خواندن جریان ورود', 'read', [q('before', 'پیش از ورود چه چیزی render می‌شود؟', ['Dashboard', 'Login', 'هر دو', 'هیچ‌کدام'], 1, 'user برابر null است؛ شرط !user درست است و Login برگردانده می‌شود.', 'function App(){ const [user,setUser]=useState(null);\n if(!user) return <Login onLogin={setUser} />;\n return <Dashboard user={user} />; }'), q('owner', 'state کاربر متعلق به کدام کامپوننت است؟', ['Login', 'Dashboard', 'App'], 2, 'useState داخل App فراخوانی شده؛ Login از callback والد استفاده می‌کند.'), q('callback', 'کدام اتفاق می‌تواند Dashboard را ظاهر کند؟', ['Login callback را با user فراخوانی کند', 'تغییر یک متغیر معمولی', 'حذف prop user'], 0, 'onLogin همان setter در App است. تغییر state، App را دوباره فراخوانی می‌کند.')], ['state-counter']),
];

export const contentHelpers = { lesson, quiz, q, t, text, click, input, count };
