import type { Chapter, Concept, KnowledgeRoom, SkillDefinition } from '@react-quest/shared';

const concept = (title: string, paragraphs: string[], example: string, visual: Concept['visual'], reference: string): Concept => ({ title, paragraphs, example, visual, reference });
export const chapters: Chapter[] = [
  { id: 0, title: 'پیش‌نیازهای JavaScript', roomId: 'bedroom', skills: ['javascript'], prerequisites: [], description: 'قبل از React، داده و تابع را بشناس.', concept: concept('داده را تغییر بده، اصل داده را نگه دار', ['map آرایهٔ جدید می‌سازد؛ filter اعضای مناسب را نگه می‌دارد. خروجی تابع باید به ورودی‌اش وابسته باشد.', 'Destructuring داده را باز می‌کند. Spread یک کپی سطحی می‌سازد؛ اشیای تو‌در‌تو همچنان می‌توانند مشترک باشند.'], 'const names = users.filter(u => u.active).map(u => u.name);', 'props', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map') },
  { id: 1, title: 'پایه‌های React', roomId: 'bedroom', skills: ['jsx'], prerequisites: [], description: 'رابط، خروجی یک تابع از داده‌هاست.', concept: concept('JSX یک توصیف از رابط است', ['کامپوننت تابعی با نام بزرگ است که JSX برمی‌گرداند. آکولادها عبارت JavaScript را وارد JSX می‌کنند.', 'React ابتدا کامپوننت را فراخوانی می‌کند، سپس تغییر لازم را روی DOM اعمال می‌کند. یک render الزاماً به معنی تغییر DOM نیست.'], 'function Greeting({ name }) { return <h1>Hello {name}</h1>; }', 'render', 'https://react.dev/learn/writing-markup-with-jsx') },
  { id: 2, title: 'کامپوننت‌ها و Props', roomId: 'workshop', skills: ['components', 'props'], prerequisites: ['hello-react'], description: 'قطعه‌های کوچک، قراردادهای روشن.', concept: concept('داده از والد به فرزند می‌رود', ['Props ورودی فقط‌خواندنی کامپوننت‌اند. یک کارت باید با دادهٔ جدید هم کار کند، نه فقط نمونهٔ اولیه.', 'با children می‌توان ظاهر یک قاب را از محتوای آن جدا کرد. کامپوننت کوچک به معنی شکستن هر خط به یک فایل نیست.'], 'function Panel({ children }) { return <section>{children}</section>; }', 'props', 'https://react.dev/learn/passing-props-to-a-component') },
  { id: 3, title: 'State و رویدادها', roomId: 'bedroom', skills: ['state', 'events'], prerequisites: ['profile-card'], description: 'دادهٔ متغیر و رابط همگام.', concept: concept('هر render یک snapshot دارد', ['متغیر معمولی باعث render دوباره نمی‌شود. useState مقدار را بین renderها نگه می‌دارد و setter درخواست تغییر می‌دهد.', 'دو setCount(count + 1) در یک handler یک مقدار یکسان را صف می‌کنند. دو updater به شکل n => n + 1 روی نتیجهٔ قبلی اعمال می‌شوند.', 'در رویدادها تابع را بده؛ نوشتن onClick={handleClick()} آن را هنگام render اجرا می‌کند.'], 'setCount(n => n + 1);\nsetCount(n => n + 1);', 'state', 'https://react.dev/learn/queueing-a-series-of-state-updates') },
  { id: 4, title: 'رندر شرطی و لیست‌ها', roomId: 'workshop', skills: ['lists'], prerequisites: ['state-counter'], description: 'داده‌ها را به رابط تبدیل کن.', concept: concept('هویت عضو لیست مهم است', ['برای رندر آرایه از map استفاده کن. key باید هویت پایدار داده باشد، نه شمارهٔ تصادفی یا index یک لیست قابل تغییر.', 'State را مستقیماً mutate نکن؛ map، filter و spread نسخهٔ جدید تولید می‌کنند. دادهٔ مشتق‌شده مثل لیست فیلترشده را لازم نیست جدا در state ذخیره کنی.'], 'todos.map(todo => <TodoItem key={todo.id} todo={todo} />)', 'render', 'https://react.dev/learn/rendering-lists') },
  { id: 5, title: 'فرم‌ها', roomId: 'workshop', skills: ['forms'], prerequisites: ['todo-render'], description: 'ورودی کاربر، اعتبارسنجی و submit.', concept: concept('یک منبع حقیقت برای ورودی', ['در input کنترل‌شده، value از state می‌آید و onChange همان state را به‌روز می‌کند.', 'submit فرم را با preventDefault کنترل کن. برچسب قابل دسترس و بازخورد اعتبارسنجی بخشی از رفتار درست فرم‌اند.'], '<input value={name} onChange={e => setName(e.target.value)} />', 'state', 'https://react.dev/reference/react-dom/components/input') },
  { id: 6, title: 'Hooks و Effectها', roomId: 'laboratory', skills: ['effects', 'refs', 'custom-hooks'], prerequisites: ['form-name'], description: 'همگام‌سازی با بیرون و منطق قابل استفادهٔ دوباره.', concept: concept('Effect برای همگام‌سازی است', ['Effect را برای محاسبهٔ دادهٔ مشتق‌شده به کار نبر. dependencyها باید مقادیر واکنشی استفاده‌شده را منعکس کنند.', 'هر interval، listener یا درخواست باید در صورت نیاز cleanup داشته باشد. updater تابعی می‌تواند وابستگی به snapshot قبلی state را حذف کند.', 'useRef دادهٔ پایدار بدون render نگه می‌دارد؛ custom hook منطق را به اشتراک می‌گذارد، نه یک state مشترک بین همهٔ مصرف‌کننده‌ها.'], 'useEffect(() => {\n  const id = setInterval(() => setCount(n => n + 1), 1000);\n  return () => clearInterval(id);\n}, []);', 'effect', 'https://react.dev/learn/synchronizing-with-effects') },
  { id: 7, title: 'دریافت داده', roomId: 'server-room', skills: ['api'], prerequisites: ['effect-greeting'], description: 'loading، error و پاسخ‌های دیررس.', concept: concept('درخواست هم می‌تواند شکست بخورد', ['loading، success و error حالت‌های متفاوت‌اند. پاسخ ناموفق HTTP را بررسی کن؛ fetch برای هر status ناموفق لزوماً reject نمی‌شود.', 'در cleanup از AbortController یا محافظ پاسخ قدیمی استفاده کن تا نتیجهٔ یک درخواست قدیمی جای دادهٔ جدید را نگیرد.', 'API این آزمایشگاه شبیه‌سازی‌شده و قطعی است؛ می‌توانی بدون کلید API، loading و خطا را تست کنی.'], 'const controller = new AbortController();\nfetch("/api/weather", { signal: controller.signal });\n// cleanup: controller.abort()', 'effect', 'https://react.dev/learn/you-might-not-need-an-effect#fetching-data') },
  { id: 8, title: 'React Router', roomId: 'station', skills: ['routing'], prerequisites: ['fetch-weather'], description: 'صفحه، مسیر و layout مشترک.', concept: concept('URL بخشی از وضعیت برنامه است', ['Routes مسیر را به عنصر رابط وصل می‌کند. Link جابه‌جایی را به Router واگذار می‌کند.', 'مسیرهای تودرتو برای layout مشترک از Outlet استفاده می‌کنند. در پیش‌نمایش از MemoryRouter استفاده می‌کنیم تا درس از آدرس سایت جدا باشد.'], '<Route path="/" element={<Layout />}><Route path="help" element={<Help />} /></Route>', 'router', 'https://reactrouter.com/start/declarative/routing') },
  { id: 9, title: 'مدیریت State', roomId: 'control-room', skills: ['reducer'], prerequisites: ['state-counter'], description: 'رویدادها را به تغییرات قابل پیش‌بینی تبدیل کن.', concept: concept('Action، سپس Reducer', ['useReducer منطق تغییر state را متمرکز می‌کند. reducer باید خالص باشد؛ درخواست شبکه جای دیگری انجام می‌شود.', 'Redux Toolkit برای state مشترک از store، action و reducer استفاده می‌کند. همهٔ stateهای یک فرم لازم نیست وارد Redux شوند.'], 'dispatch({ type: "added", text });\n// reducer(state, action) -> nextState', 'redux', 'https://redux-toolkit.js.org/tutorials/quick-start') },
  { id: 10, title: 'React Query', roomId: 'server-room', skills: ['query'], prerequisites: ['fetch-weather'], description: 'State سرور، cache و تازگی داده.', concept: concept('Cache با state محلی فرق دارد', ['Query key هویت داده است. متغیری که queryFn به آن وابسته است باید در key هم منعکس شود.', 'React Query وضعیت دریافت، خطا، cache و refetch را مدیریت می‌کند. staleTime مدت تازگی داده است، نه مدت نگهداری آن در cache.', 'برای تغییر سرور از mutation استفاده کن و دادهٔ مرتبط را invalidate یا به‌روز کن.'], 'useQuery({ queryKey: ["weather", city], queryFn: () => loadWeather(city), staleTime: 60000 })', 'query', 'https://tanstack.com/query/latest/docs/framework/react/quick-start') },
  { id: 11, title: 'کارایی', roomId: 'laboratory', skills: ['performance'], prerequisites: ['state-counter'], description: 'اول اندازه بگیر، بعد بهینه کن.', concept: concept('Memoization همیشه لازم نیست', ['useMemo نتیجهٔ محاسبه و useCallback هویت تابع را cache می‌کنند؛ React.memo می‌تواند render ناشی از props یکسان را رد کند.', 'جمع دو عدد معمولاً نیازی به useMemo ندارد. dependency اشتباه می‌تواند نتیجهٔ قدیمی بدهد. memoization تضمین منطقی برنامه نیست.', 'شمارندهٔ فراخوانی کامپوننت در ابزار این درس مشاهدهٔ اجراست؛ زمان‌های آزمایشگاه benchmark تولید نیستند.'], 'const visible = useMemo(() => filter(items, query), [items, query]);', 'render', 'https://react.dev/reference/react/useMemo') },
  { id: 12, title: 'تست رفتار رابط', roomId: 'testing-lab', skills: ['testing'], prerequisites: ['state-counter'], description: 'تست باید خرابی را پیدا کند.', concept: concept('مثل کاربر تست کن', ['عنصر را با role و نام قابل دسترس پیدا کن، یک تعامل انجام بده و نتیجهٔ قابل مشاهده را بررسی کن.', 'تستی که فقط وجود یک button را می‌سنجد، خراب بودن شمارنده را تشخیص نمی‌دهد. تستت روی یک نسخهٔ خراب هم اجرا می‌شود تا این تفاوت روشن شود.'], 'render(<App />);\nfireEvent.click(screen.getByRole("button", { name: "+1" }));\nexpect(screen.getByRole("status")).toHaveTextContent("1");', 'render', 'https://testing-library.com/docs/react-testing-library/intro/') },
  { id: 13, title: 'معماری و بازآرایی', roomId: 'workshop', skills: ['architecture'], prerequisites: ['todo-add'], description: 'رفتار را نگه دار، ساختار را روشن‌تر کن.', concept: concept('مرز بر اساس مسئولیت', ['TodoItem یک عضو را نمایش می‌دهد، TodoList لیست را، و useTodos منطق تغییر و ذخیره را نگه می‌دارد.', 'هدف کاهش تعداد خط به هر قیمت نیست. تست رفتار باید قبل و بعد از بازآرایی ثابت بماند؛ محدودیت خط فقط تمرین جداکردن مسئولیت‌هاست.'], 'function App() {\n  const todos = useTodos();\n  return <TodoList {...todos} />;\n}', 'props', 'https://react.dev/learn/reusing-logic-with-custom-hooks') },
  { id: 14, title: 'پروژهٔ نهایی', roomId: 'workshop', skills: ['architecture', 'forms', 'lists', 'state'], prerequisites: ['todo-hook', 'query-cache'], description: 'یک برنامه از صفحهٔ خالی بساز و از تصمیم‌هایت دفاع کن.', concept: concept('Build → Debug → Review', ['نیازمندی را به رفتار قابل تست تبدیل کن. پیش از انتخاب کتابخانه، منبع هر state و مرز هر کامپوننت را مشخص کن.', 'اپ مدیریت مطالعه باید افزودن، انجام‌دادن، فیلتر و ذخیره را پشتیبانی کند. پس از عبور از تست‌ها، کیفیت ساختار را مرور کن.'], '// Your application starts here.', 'redux', 'https://react.dev/learn/thinking-in-react') }
];

export const skills: SkillDefinition[] = chapters.flatMap(chapter => chapter.skills.map(id => ({ id, title: ({ javascript: 'JavaScript', jsx: 'JSX', components: 'کامپوننت', props: 'Props', state: 'State', events: 'رویدادها', lists: 'لیست‌ها', forms: 'فرم‌ها', effects: 'Effect و cleanup', refs: 'Refs', 'custom-hooks': 'Custom Hooks', api: 'API', routing: 'Routing', reducer: 'Reducer / Redux', query: 'React Query', performance: 'کارایی', testing: 'تست', architecture: 'معماری' } as Record<string, string>)[id] ?? id, chapterId: chapter.id, prerequisites: ({ props: ['components'], state: ['jsx'], events: ['jsx'], lists: ['state'], forms: ['state'], effects: ['state'], refs: ['state'], 'custom-hooks': ['effects'], api: ['effects'], routing: ['components'], reducer: ['state'], query: ['api'], performance: ['components'], testing: ['state'], architecture: ['components', 'custom-hooks'] } as Record<string, string[]>)[id] ?? [] }))).filter((skill, index, all) => all.findIndex(item => item.id === skill.id) === index);

export const rooms: KnowledgeRoom[] = [
  { id: 'bedroom', title: 'اتاق شروع', subtitle: 'پایه‌های React', mastery: [], color: '#90a78b', chapters: [0, 1, 3], emblem: 'REACT BASICS' },
  { id: 'workshop', title: 'کارگاه کامپوننت', subtitle: 'Components · Forms · Architecture', mastery: ['components'], color: '#b2956d', chapters: [2, 4, 5, 13, 14], emblem: 'BUILD SOMETHING' },
  { id: 'laboratory', title: 'آزمایشگاه Hooks', subtitle: 'Effects · Refs · Performance', mastery: ['state'], color: '#799ca7', chapters: [6, 11], emblem: 'HOOKS LAB' },
  { id: 'library', title: 'کتابخانه', subtitle: 'توضیح‌ها و مستندات', mastery: [], color: '#a196b1', chapters: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], emblem: 'READ / THINK / TRY' },
  { id: 'server-room', title: 'مرکز ارتباطات', subtitle: 'API · React Query', mastery: ['api'], color: '#6c9d91', chapters: [7, 10], emblem: 'SERVER DATA' },
  { id: 'control-room', title: 'اتاق کنترل', subtitle: 'Reducer · Redux', mastery: ['reducer'], color: '#8f93b8', chapters: [9], emblem: 'ACTION > STATE' },
  { id: 'station', title: 'ایستگاه مسیرها', subtitle: 'React Router', mastery: ['routing'], color: '#ba986f', chapters: [8], emblem: 'NEXT DESTINATION' },
  { id: 'testing-lab', title: 'آزمایشگاه تست', subtitle: 'Testing Library', mastery: ['testing'], color: '#86a076', chapters: [12], emblem: 'TEST THE BEHAVIOR' },
  { id: 'interview', title: 'اتاق مصاحبه', subtitle: 'تصمیم فنی و کدنویسی', mastery: ['components', 'state', 'effects'], color: '#ad8791', chapters: [11, 6], emblem: 'EXPLAIN YOUR WHY' }
];
export const challengeKinds = { write: 'نوشتن کد', debug: 'رفع باگ', predict: 'پیش‌بینی خروجی', read: 'خواندن کد', complete: 'تکمیل کد', refactor: 'بازآرایی', feature: 'ساخت قابلیت', boss: 'چالش نهایی' } as const;
